// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: rpc.proto

package server

import (
	"context"

	"server/app/rpc/internal/logic"
	"server/app/rpc/internal/svc"
	"server/app/rpc/pb"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

// edge 进行登录
func (s *RpcServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *RpcServer) Logout(ctx context.Context, in *pb.LogoutRequest) (*pb.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *RpcServer) PostMessage(ctx context.Context, in *pb.PostMsg) (*pb.PostResponse, error) {
	l := logic.NewPostMessageLogic(ctx, s.svcCtx)
	return l.PostMessage(in)
}

// 业务部分
func (s *RpcServer) AuthLogin(ctx context.Context, in *pb.AuthLoginRequest) (*pb.AuthLoginResponse, error) {
	l := logic.NewAuthLoginLogic(ctx, s.svcCtx)
	return l.AuthLogin(in)
}
