// Code generated by goctl. DO NOT EDIT.
// Source: rpc.proto

package server

import (
	"context"

	"server/app/rpc/internal/logic"
	"server/app/rpc/internal/svc"
	"server/app/rpc/pb"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *RpcServer) Logout(ctx context.Context, in *pb.LogoutRequest) (*pb.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *RpcServer) PostMessage(ctx context.Context, in *pb.PostMsg) (*pb.PostResponse, error) {
	l := logic.NewPostMessageLogic(ctx, s.svcCtx)
	return l.PostMessage(in)
}

// 用户相关接口
func (s *RpcServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoRequest) (*pb.GetUserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// 好友相关接口
func (s *RpcServer) GetFriendList(ctx context.Context, in *pb.GetFriendListRequest) (*pb.GetFriendListResponse, error) {
	l := logic.NewGetFriendListLogic(ctx, s.svcCtx)
	return l.GetFriendList(in)
}

func (s *RpcServer) AddFriend(ctx context.Context, in *pb.AddFriendRequest) (*pb.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *RpcServer) DeleteFriend(ctx context.Context, in *pb.DeleteFriendRequest) (*pb.DeleteFriendResponse, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

// 群组相关接口
func (s *RpcServer) GetGroupList(ctx context.Context, in *pb.GetGroupListRequest) (*pb.GetGroupListResponse, error) {
	l := logic.NewGetGroupListLogic(ctx, s.svcCtx)
	return l.GetGroupList(in)
}

func (s *RpcServer) CreateGroup(ctx context.Context, in *pb.CreateGroupRequest) (*pb.CreateGroupResponse, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}
