// Code generated by goctl. DO NOT EDIT.
// Source: rpc.proto

package rpc

import (
	"context"

	"server/app/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Nil = pb.Nil

	Rpc interface {
		// @desc ping
		Ping(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*Nil, error)
	}

	defaultRpc struct {
		cli zrpc.Client
	}
)

func NewRpc(cli zrpc.Client) Rpc {
	return &defaultRpc{
		cli: cli,
	}
}

// @desc ping
func (m *defaultRpc) Ping(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*Nil, error) {
	client := pb.NewRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
