// Code generated by goctl. DO NOT EDIT.
package types

type AddFriendRequest struct {
	FriendUsername string `json:"friend_username"`
	Remark         string `json:"remark,omitempty"`
}

type CommonResponse struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type FriendInfo struct {
	UserId   uint64 `json:"user_id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Status   int32  `json:"status"`
	LastSeen int64  `json:"last_seen"`
}

type FriendListResponse struct {
	Code    int32        `json:"code"`
	Message string       `json:"message"`
	Friends []FriendInfo `json:"friends,omitempty"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	DeviceId string `json:"device_id"`
}

type LoginResponse struct {
	Code     int32  `json:"code"`
	Message  string `json:"message"`
	Token    string `json:"token,omitempty"`
	UserInfo struct {
		UserId    uint64 `json:"user_id"`
		Username  string `json:"username"`
		Nickname  string `json:"nickname"`
		Avatar    string `json:"avatar"`
		Email     string `json:"email"`
		CreatedAt int64  `json:"created_at"`
	} `json:"user_info,omitempty"`
}

type UserInfo struct {
	UserId    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Email     string `json:"email"`
	CreatedAt int64  `json:"created_at"`
}
