// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AuthLoginReply struct {
	Token         string
	Authorization string
}

type AuthLoginReq struct {
	Username string
	Password string
}
