// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/SpectatorNan/gorm-zero/gormc/pagex"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheZeroimImUserFriendsIdPrefix             = "cache:zeroim:imUserFriends:id:"
	cacheZeroimImUserFriendsUserIdFriendIdPrefix = "cache:zeroim:imUserFriends:userId:friendId:"
)

type (
	imUserFriendsModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *ImUserFriends) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []ImUserFriends) error
		FindOne(ctx context.Context, id uint64) (*ImUserFriends, error)
		FindPageList(ctx context.Context, page *pagex.ListReq, orderBys []pagex.OrderBy,
			orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]ImUserFriends, int64, error)
		FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*ImUserFriends, error)
		Update(ctx context.Context, tx *gorm.DB, data *ImUserFriends) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []ImUserFriends) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []ImUserFriends) error

		Delete(ctx context.Context, tx *gorm.DB, id uint64) error
	}

	defaultImUserFriendsModel struct {
		gormc.CachedConn
		table string
	}

	ImUserFriends struct {
		Id         uint64         `gorm:"column:id;primary_key"`
		UserId     uint64         `gorm:"column:user_id"`     // 用户ID
		FriendId   uint64         `gorm:"column:friend_id"`   // 好友ID
		Remark     string         `gorm:"column:remark"`      // 好友备注
		Status     int64          `gorm:"column:status"`      // 关系状态: 0-已删除, 1-正常, 2-拉黑
		DeleteFlag int64          `gorm:"column:delete_flag"` // 删除标记: 0-未删除, 1-已删除
		CreatedAt  time.Time      `gorm:"column:created_at"`  // 添加时间
		UpdatedAt  time.Time      `gorm:"column:updated_at"`
		DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;index"` // 删除时间
	}
)

func (ImUserFriends) TableName() string {
	return "`im_user_friends`"
}

func newImUserFriendsModel(db *gorm.DB, c cache.CacheConf) *defaultImUserFriendsModel {
	return &defaultImUserFriendsModel{
		CachedConn: gormc.NewConn(db, c),
		table:      "`im_user_friends`",
	}
}

func (m *defaultImUserFriendsModel) GetCacheKeys(data *ImUserFriends) []string {
	if data == nil {
		return []string{}
	}
	zeroimImUserFriendsIdKey := fmt.Sprintf("%s%v", cacheZeroimImUserFriendsIdPrefix, data.Id)
	zeroimImUserFriendsUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheZeroimImUserFriendsUserIdFriendIdPrefix, data.UserId, data.FriendId)
	cacheKeys := []string{
		zeroimImUserFriendsIdKey, zeroimImUserFriendsUserIdFriendIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultImUserFriendsModel) Insert(ctx context.Context, tx *gorm.DB, data *ImUserFriends) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultImUserFriendsModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []ImUserFriends) error {

	err := batchx.BatchExecCtxV2(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		for _, v := range news {
			if err := db.Create(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)
	return err
}

func (m *defaultImUserFriendsModel) FindOne(ctx context.Context, id uint64) (*ImUserFriends, error) {
	zeroimImUserFriendsIdKey := fmt.Sprintf("%s%v", cacheZeroimImUserFriendsIdPrefix, id)
	var resp ImUserFriends
	err := m.QueryCtx(ctx, &resp, zeroimImUserFriendsIdKey, func(conn *gorm.DB) error {
		return conn.Model(&ImUserFriends{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultImUserFriendsModel) FindPageList(ctx context.Context, page *pagex.ListReq, orderBys []pagex.OrderBy,
	orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]ImUserFriends, int64, error) {
	formatDB := func(conn *gorm.DB) (*gorm.DB, *gorm.DB) {
		db := conn.Model(&ImUserFriends{})
		if whereClause != nil {
			db = whereClause(db)
		}
		return db, nil
	}
	res, total, err := pagex.FindPageListMultiOrderBy[ImUserFriends](ctx, m, page, orderBys, orderKeys, formatDB)
	return res, total, err
}

func (m *defaultImUserFriendsModel) FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*ImUserFriends, error) {
	zeroimImUserFriendsUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheZeroimImUserFriendsUserIdFriendIdPrefix, userId, friendId)
	var resp ImUserFriends
	err := m.QueryRowIndexCtx(ctx, &resp, zeroimImUserFriendsUserIdFriendIdKey, m.formatPrimary, func(conn *gorm.DB, v interface{}) (interface{}, error) {
		if err := conn.Model(&ImUserFriends{}).Where("`user_id` = ? and `friend_id` = ?", userId, friendId).Take(&resp).Error; err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImUserFriendsModel) Update(ctx context.Context, tx *gorm.DB, data *ImUserFriends) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultImUserFriendsModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []ImUserFriends) error {
	clearData := make([]ImUserFriends, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtxV2(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		for _, v := range news {
			if err := db.Save(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)

	return err
}

func (m *defaultImUserFriendsModel) Delete(ctx context.Context, tx *gorm.DB, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&ImUserFriends{}, id).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultImUserFriendsModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []ImUserFriends) error {
	err := batchx.BatchExecCtxV2(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		for _, v := range datas {
			if err := db.Delete(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)
	return err
}

func (m *defaultImUserFriendsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheZeroimImUserFriendsIdPrefix, primary)
}

func (m *defaultImUserFriendsModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&ImUserFriends{}).Where("`id` = ?", primary).Take(v).Error
}
