// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/SpectatorNan/gorm-zero/gormc/pagex"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheZeroimImUsersUserIdPrefix   = "cache:zeroim:imUsers:userId:"
	cacheZeroimImUsersUsernamePrefix = "cache:zeroim:imUsers:username:"
)

type (
	imUsersModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *ImUsers) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []ImUsers) error
		FindOne(ctx context.Context, userId uint64) (*ImUsers, error)
		FindPageList(ctx context.Context, page *pagex.ListReq, orderBys []pagex.OrderBy,
			orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]ImUsers, int64, error)
		FindOneByUsername(ctx context.Context, username string) (*ImUsers, error)
		Update(ctx context.Context, tx *gorm.DB, data *ImUsers) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []ImUsers) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []ImUsers) error

		Delete(ctx context.Context, tx *gorm.DB, userId uint64) error
	}

	defaultImUsersModel struct {
		gormc.CachedConn
		table string
	}

	ImUsers struct {
		UserId        uint64         `gorm:"column:user_id;primary_key"` // 用户ID
		Username      string         `gorm:"column:username"`            // 用户名
		Password      string         `gorm:"column:password"`            // 密码(加密后)
		Nickname      string         `gorm:"column:nickname"`            // 昵称
		Avatar        string         `gorm:"column:avatar"`              // 头像URL
		Email         string         `gorm:"column:email"`               // 邮箱
		Phone         string         `gorm:"column:phone"`               // 手机号
		Gender        int64          `gorm:"column:gender"`              // 性别: 0-未知, 1-男, 2-女
		Birthday      time.Time      `gorm:"column:birthday"`            // 生日
		Signature     string         `gorm:"column:signature"`           // 个性签名
		Status        int64          `gorm:"column:status"`              // 账号状态: 0-禁用, 1-正常
		LastLoginTime time.Time      `gorm:"column:last_login_time"`     // 最后登录时间
		LastLoginIp   string         `gorm:"column:last_login_ip"`       // 最后登录IP
		DeleteFlag    int64          `gorm:"column:delete_flag"`         // 删除标记: 0-未删除, 1-已删除
		CreatedAt     time.Time      `gorm:"column:created_at"`          // 创建时间
		UpdatedAt     time.Time      `gorm:"column:updated_at"`          // 更新时间
		DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;index"`    // 删除时间
	}
)

func (ImUsers) TableName() string {
	return "`im_users`"
}

func newImUsersModel(db *gorm.DB, c cache.CacheConf) *defaultImUsersModel {
	return &defaultImUsersModel{
		CachedConn: gormc.NewConn(db, c),
		table:      "`im_users`",
	}
}

func (m *defaultImUsersModel) GetCacheKeys(data *ImUsers) []string {
	if data == nil {
		return []string{}
	}
	zeroimImUsersUserIdKey := fmt.Sprintf("%s%v", cacheZeroimImUsersUserIdPrefix, data.UserId)
	zeroimImUsersUsernameKey := fmt.Sprintf("%s%v", cacheZeroimImUsersUsernamePrefix, data.Username)
	cacheKeys := []string{
		zeroimImUsersUserIdKey, zeroimImUsersUsernameKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultImUsersModel) Insert(ctx context.Context, tx *gorm.DB, data *ImUsers) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultImUsersModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []ImUsers) error {

	err := batchx.BatchExecCtxV2(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		for _, v := range news {
			if err := db.Create(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)
	return err
}

func (m *defaultImUsersModel) FindOne(ctx context.Context, userId uint64) (*ImUsers, error) {
	zeroimImUsersUserIdKey := fmt.Sprintf("%s%v", cacheZeroimImUsersUserIdPrefix, userId)
	var resp ImUsers
	err := m.QueryCtx(ctx, &resp, zeroimImUsersUserIdKey, func(conn *gorm.DB) error {
		return conn.Model(&ImUsers{}).Where("`user_id` = ?", userId).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultImUsersModel) FindPageList(ctx context.Context, page *pagex.ListReq, orderBys []pagex.OrderBy,
	orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]ImUsers, int64, error) {
	formatDB := func(conn *gorm.DB) (*gorm.DB, *gorm.DB) {
		db := conn.Model(&ImUsers{})
		if whereClause != nil {
			db = whereClause(db)
		}
		return db, nil
	}
	res, total, err := pagex.FindPageListMultiOrderBy[ImUsers](ctx, m, page, orderBys, orderKeys, formatDB)
	return res, total, err
}

func (m *defaultImUsersModel) FindOneByUsername(ctx context.Context, username string) (*ImUsers, error) {
	zeroimImUsersUsernameKey := fmt.Sprintf("%s%v", cacheZeroimImUsersUsernamePrefix, username)
	var resp ImUsers
	err := m.QueryRowIndexCtx(ctx, &resp, zeroimImUsersUsernameKey, m.formatPrimary, func(conn *gorm.DB, v interface{}) (interface{}, error) {
		if err := conn.Model(&ImUsers{}).Where("`username` = ?", username).Take(&resp).Error; err != nil {
			return nil, err
		}
		return resp.UserId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImUsersModel) Update(ctx context.Context, tx *gorm.DB, data *ImUsers) error {
	old, err := m.FindOne(ctx, data.UserId)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultImUsersModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []ImUsers) error {
	clearData := make([]ImUsers, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtxV2(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		for _, v := range news {
			if err := db.Save(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)

	return err
}

func (m *defaultImUsersModel) Delete(ctx context.Context, tx *gorm.DB, userId uint64) error {
	data, err := m.FindOne(ctx, userId)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&ImUsers{}, userId).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultImUsersModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []ImUsers) error {
	err := batchx.BatchExecCtxV2(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		for _, v := range datas {
			if err := db.Delete(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)
	return err
}

func (m *defaultImUsersModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheZeroimImUsersUserIdPrefix, primary)
}

func (m *defaultImUsersModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&ImUsers{}).Where("`user_id` = ?", primary).Take(v).Error
}
